# Generated by Django 3.2.15 on 2023-04-21 17:40

from django.db import migrations, models
from django.db.models import Q


def remove_null_units(apps, schema_editor):
    Unit = apps.get_model('company', 'Unit')
    Unit.objects.filter(Q(code__isnull=True) | Q(code='')).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    # https://stackoverflow.com/a/39541048
    # To solve django.db.utils.OperationalError: cannot ALTER TABLE "company_unit" because it has pending trigger events
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    remove_null_units, reverse_code=migrations.RunPython.noop
                )
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='unit',
                    name='code',
                    field=models.CharField(error_messages={'unique': 'Подразделение с таким кодом уже существует'}, max_length=20, unique=True, verbose_name='Код подразделения'),
                ),
            ]
        )
    ]
