# Generated by Django 3.2.16 on 2023-10-30 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('company', '0002_alter_unit_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='sap_id',
            field=models.IntegerField(verbose_name='Id города sap', null=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap_city_id', models.IntegerField(verbose_name='Id города sap', null=True)),
                ('sap_id', models.IntegerField(verbose_name='Id код офиса')),
                ('street', models.CharField(max_length=240, verbose_name='Название улицы')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offices', to='company.city')),
            ],
            options={
                'verbose_name': 'Офис',
                'verbose_name_plural': 'Офисы',
            },
        ),
    ]
