# Generated by Django 3.2.16 on 2023-11-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20231109_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='code',
            field=models.CharField(default=1, max_length=512, verbose_name='Id штатной должности'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='position',
            name='code',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Id штатной должности'),
        ),
    ]
