# Generated by Django 3.2.16 on 2023-12-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_position_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='selection_type',
            field=models.CharField(choices=[('mass', 'Массовый'), ('professional', 'Профессиональный')], default='professional', max_length=217, verbose_name='Тип подбора'),
        ),
    ]
