# Generated by Django 3.2.16 on 2023-12-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_position_selection_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='building',
            field=models.CharField(blank=True, max_length=250, verbose_name='Здание'),
        ),
    ]
