# Generated by Django 3.2.16 on 2023-12-12 09:35

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models

import company.models


def prepare_to_migration(apps, _schema_editor):
    position_model = apps.get_model('company', 'Position')
    position_model.objects.all().update(code=models.F('id'))


def default_unit():
    unit, _ = company.models.Unit.objects.get_or_create(
        code=settings.ROOT_DEPARTMENT_CODE, defaults={'name': settings.ROOT_DEPARTMENT_NAME}
    )
    return unit.id


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_building_to_office'),
    ]

    operations = [
        migrations.RunPython(prepare_to_migration, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='position',
            name='units',
        ),
        migrations.AddField(
            model_name='position',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='unit',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='position',
            name='unit',
            field=models.ForeignKey(default=default_unit, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='company.unit', verbose_name='Подразделение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='position',
            name='code',
            field=models.CharField(max_length=512, unique=True, verbose_name='Id штатной должности'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='company.unit'),
        ),
        migrations.DeleteModel(
            name='PositionToUnit',
        ),
    ]
