# Generated by Django 3.2.16 on 2023-12-13 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0008_auto_20231212_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinate_units', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель'),
        ),
    ]
