# Generated by Django 3.2.16 on 2023-12-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_unit_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='branch',
            field=models.CharField(blank=True, max_length=250, verbose_name='Название филиала'),
        ),
        migrations.AddField(
            model_name='office',
            name='company',
            field=models.CharField(blank=True, max_length=250, verbose_name='Название компании'),
        ),
        migrations.AddField(
            model_name='office',
            name='sap_branch_id',
            field=models.CharField(blank=True, max_length=150, verbose_name='Id код филиала'),
        ),
        migrations.AddField(
            model_name='office',
            name='sap_company_id',
            field=models.CharField(blank=True, max_length=150, verbose_name='Id компании sap'),
        ),
        migrations.AlterField(
            model_name='office',
            name='street',
            field=models.CharField(blank=True, max_length=240, verbose_name='Название улицы'),
        ),
    ]
