# Generated by Django 3.2.15 on 2022-10-24 17:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial_core_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок баннера')),
                ('text', models.CharField(max_length=1000, verbose_name='Текст баннера')),
            ],
            options={
                'verbose_name': 'Баннер в шапке страницы',
                'verbose_name_plural': 'Баннеры в шапке страницы',
            },
        ),
        migrations.CreateModel(
            name='InterestingCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('url', models.URLField(blank=True, max_length=1000, null=True, verbose_name='Адрес ссылки')),
                ('url_display', models.CharField(blank=True, max_length=250, null=True, verbose_name='Текст ссылки')),
                ('active', models.BooleanField(default=True, verbose_name='Активна')),
                ('priority', models.PositiveSmallIntegerField(default=10, help_text='Карточка с наименьшим значением будет выдаваться первой', verbose_name='Приоритет')),
                ('image', models.ImageField(upload_to=core.utils.file_path, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Карточка "Интересное для тебя"',
                'verbose_name_plural': 'Карточки "Интересное для тебя"',
            },
        ),
        migrations.CreateModel(
            name='PollResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=700, verbose_name='Текст результата')),
            ],
            options={
                'verbose_name': 'Результат теста',
                'verbose_name_plural': 'Результаты теста',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Текст вопроса')),
                ('priority', models.PositiveSmallIntegerField(default=100, help_text='Вопрос с наименьшим значением будет выдаваться первым. Диапазон значений: [1;100]', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Приоритет')),
                ('career_type', models.ForeignKey(help_text='К какому карьерному типу предпочтительнее будет определить сотрудника при положительном ответе на текущий вопрос', on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='core.careertype', verbose_name='Категория положительного ответа на текущий вопрос')),
            ],
            options={
                'verbose_name': 'Вопрос для теста',
                'verbose_name_plural': 'Вопросы для теста',
            },
        ),
        migrations.CreateModel(
            name='PollResultToCareerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pollresult', verbose_name='Ответ')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.careertype', verbose_name='Тип карьеры')),
            ],
        ),
        migrations.AddField(
            model_name='pollresult',
            name='career_types',
            field=models.ManyToManyField(help_text='К каким карьерным типам относится текущий результат', related_name='poll_results', through='main.PollResultToCareerType', to='core.CareerType', verbose_name='Типы карьеры'),
        ),
        migrations.CreateModel(
            name='EmployeeCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('url', models.URLField(blank=True, max_length=1000, null=True, verbose_name='Адрес ссылки')),
                ('url_display', models.CharField(blank=True, max_length=250, null=True, verbose_name='Текст ссылки')),
                ('active', models.BooleanField(default=True, verbose_name='Активна')),
                ('priority', models.PositiveSmallIntegerField(default=10, help_text='Карточка с наименьшим значением будет выдаваться первой', verbose_name='Приоритет')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='employee_card', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Карточка "Карьера и кофе"',
                'verbose_name_plural': 'Карточки "Карьера и кофе"',
            },
        ),
        migrations.CreateModel(
            name='CareerTypeCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('url', models.URLField(blank=True, max_length=1000, null=True, verbose_name='Адрес ссылки')),
                ('url_display', models.CharField(blank=True, max_length=250, null=True, verbose_name='Текст ссылки')),
                ('active', models.BooleanField(default=True, verbose_name='Активна')),
                ('priority', models.PositiveSmallIntegerField(default=10, help_text='Карточка с наименьшим значением будет выдаваться первой', verbose_name='Приоритет')),
                ('image', models.ImageField(upload_to=core.utils.file_path, verbose_name='Изображение')),
                ('career_type', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='career_card', to='core.careertype', verbose_name='Тип карьеры')),
            ],
            options={
                'verbose_name': 'Карточка "Тип карьеры"',
                'verbose_name_plural': 'Карточки "Тип карьеры"',
            },
        ),
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=core.utils.file_path, verbose_name='Изображение')),
                ('priority', models.PositiveSmallIntegerField(default=100, help_text='Изображение с наименьшим значением будет выдаваться первым. Диапазон значений: [1;100]', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Приоритет')),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner_images', to='main.banner', verbose_name='Баннер')),
            ],
            options={
                'verbose_name': 'Изображение сотрудника в шапке',
                'verbose_name_plural': 'Изображения сотрудников в шапке',
            },
        ),
    ]
