# Generated by Django 3.2.15 on 2022-11-21 14:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок в баннере теста')),
                ('text', models.CharField(blank=True, max_length=1024, verbose_name='Текст в баннере теста')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('priority',), 'verbose_name': 'Вопрос для теста', 'verbose_name_plural': 'Вопросы для теста'},
        ),
        migrations.AddField(
            model_name='employeecard',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeecard',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='question',
            name='poll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='main.poll', verbose_name='Тест'),
        ),
    ]
