# Generated by Django 3.2.15 on 2022-11-22 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_poll_employee_card_timestamped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeecard',
            name='priority',
        ),
    ]
