# Generated by Django 3.2.15 on 2023-04-12 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_remove_priority_from_parent_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerimage',
            name='file',
        ),
        migrations.RemoveField(
            model_name='bannerimage',
            name='priority',
        ),
        migrations.AddField(
            model_name='bannerimage',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='banner_image', to='users.user', verbose_name='Пользователь'),
            preserve_default=False,
        ),
    ]
