# Generated by Django 3.2.16 on 2023-12-12 10:37

from django.db import migrations, models


def move_from_fk_to_charfield(apps, schema_editor):
    """Переносим данные из поля ForeignKey в CharField."""
    CareerTypeCard = apps.get_model('main', 'CareerTypeCard')
    for card in CareerTypeCard.objects.all():
        card.career_type_string = card.career_type.slug
        card.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20230412_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='careertypecard',
            name='career_type_string',
            field=models.CharField(choices=[('expert', 'Экспертная'), ('manager', 'Управленческая'), ('project', 'Проектная'), ('all', 'Все вакансии')], error_messages={"unique": "Такой тип карьеры уже существует"}, max_length=50, null=True, verbose_name='Тип карьеры', unique=True),
        ),
        migrations.RunPython(move_from_fk_to_charfield, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='careertypecard',
            name='career_type',
        ),
        migrations.RenameField(
            model_name='careertypecard',
            old_name='career_type_string',
            new_name='type'
        ),
        migrations.AlterField(
            model_name='careertypecard',
            name='type',
            field=models.CharField(choices=[('expert', 'Экспертная'), ('manager', 'Управленческая'), ('project', 'Проектная'), ('vacancies', 'Все вакансии')], default='', error_messages={'unique': 'Такой тип карьеры уже существует'}, max_length=50, unique=True, verbose_name='Тип карьеры'),
            preserve_default=False,
        ),
    ]
