# Generated by Django 3.2.15 on 2022-10-17 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('resume', models.FileField(upload_to=core.utils.file_path, verbose_name='Резюме')),
                ('status', models.CharField(choices=[('pending', 'На согласовании'), ('approved', 'Согласована'), ('hired', 'Принят'), ('rejected', 'Отклонена'), ('reserved', 'Резерв'), ('interview', 'Собеседование'), ('canceled', 'Отозвана'), ('closed', 'Закрыта')], max_length=100, verbose_name='Статус')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replies', to=settings.AUTH_USER_MODEL, verbose_name='Соискатель')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vacancies.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Отклик на вакансию',
                'verbose_name_plural': 'Отклики на вакансию',
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(default=1, verbose_name='Номер текущего шага')),
                ('resolution', models.CharField(blank=True, choices=[('approved', 'Согласована'), ('rejected', 'Отклонена'), ('reserved', 'Резерв'), ('interview', 'Собеседование')], max_length=100, null=True, verbose_name='Решение')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий к решению')),
                ('state', models.CharField(choices=[('expected', 'Ожидает'), ('active', 'Активен'), ('hidden', 'Скрыт'), ('end', 'Завершен'), ('stop', 'Процесс остановлен')], max_length=100, verbose_name='Состояние')),
                ('status', models.CharField(choices=[('pending', 'На согласовании'), ('approved', 'Согласована'), ('hired', 'Принят'), ('rejected', 'Отклонена'), ('reserved', 'Резерв'), ('interview', 'Собеседование'), ('canceled', 'Отозвана'), ('closed', 'Закрыта')], max_length=100, verbose_name='Статус')),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='replies.reply', verbose_name='Отклик на вакансию')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Участник шага')),
            ],
            options={
                'verbose_name': 'Шаг маршрута',
                'verbose_name_plural': 'Маршруты заявок'
            },
        ),
        migrations.AddConstraint(
            model_name='step',
            constraint=models.UniqueConstraint(fields=('reply', 'index'),
                                               name='replies_step_is_unique_step_number_for_reply'),
        ),
    ]
