# Generated by Django 3.2.15 on 2022-10-24 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='role',
            field=models.CharField(choices=[('boss', 'Текущий руководитель'), ('new_boss', 'Будущий руководитель'), ('user', 'Соискатель')], default='boss', max_length=100, verbose_name='Роль'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='step',
            name='title',
            field=models.CharField(choices=[('agreement', 'Согласование'), ('interview', 'Собеседование'), ('hired', 'Принят')], default='agreement', max_length=250, verbose_name='Наименование шага'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='step',
            name='is_viewed',
            field=models.BooleanField(default=False, verbose_name='Прочитано'),
        ),
        migrations.AddField(
            model_name='step',
            name='activation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата активации шага'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replies',
                                    to='vacancies.vacancy', verbose_name='Вакансия'),
        ),
    ]
