# Generated by Django 3.2.15 on 2022-11-16 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0010_m2m_poll_poll_template_to_questions'),
        ('replies', '0002_auto_20221024_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='poll',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='replies', to='vacancies.poll', verbose_name='Опросник'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='reply',
            constraint=models.UniqueConstraint(fields=('user', 'vacancy'), name='replies_reply_is_one_user_reply_to_vacancy'),
        ),
    ]
