# Generated by Django 3.2.15 on 2023-03-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replies', '0003_auto_20221116_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='experience',
            field=models.CharField(choices=[('from_0_to_3_month', 'От 0 до 3 месяцев'), ('from_3_to_6_month', 'От 3 до 6 месяцев'), ('from_6_to_9_month', 'От 6 до 9 месяцев'), ('from_9_to_12_month', 'От 9 до 12 месяцев'), ('more_then_year', 'От года и больше')], max_length=50, verbose_name='Стаж работы сотрудника в текущей должности'),
        ),
    ]
