# Generated by Django 3.2.15 on 2023-04-03 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('replies', '0004_reply_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDriveDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата тест-драйва')),
            ],
            options={
                'verbose_name': 'Тест-драйв: дата',
                'verbose_name_plural': 'Тест-драйв: даты',
            },
        ),
        migrations.CreateModel(
            name='TestDriveReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='Дата тест-драйва')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_drive_replies', to=settings.AUTH_USER_MODEL, verbose_name='Соискатель')),
            ],
            options={
                'verbose_name': 'Тест-драйв: заявка',
                'verbose_name_plural': 'Тест-драйв: заявки',
            },
        ),
    ]
