# Generated by Django 3.2.16 on 2023-07-31 10:51

import django.db.models.deletion
from django.db import migrations, models

import core.utils


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0013_alter_vacancyreserve_requirements'),
        ('replies', '0007_auto_20230512_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='poll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replies', to='vacancies.poll', verbose_name='Опросник'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=core.utils.file_path, verbose_name='Резюме'),
        ),
    ]
