# Generated by Django 3.2.16 on 2023-09-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replies', '0008_auto_20230731_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdrivedate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
    ]
