# Generated by Django 3.2.16 on 2023-12-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replies', '0009_testdrivedate_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
