# Generated by Django 3.2.15 on 2022-10-28 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancies', '0003_poll_models_and_related'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='company_unit',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_vacancies', to=settings.AUTH_USER_MODEL, verbose_name='Опубликовавший сотрудник'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='status',
            field=models.CharField(choices=[('published', 'Опубликована'), ('accepted', 'Принят'), ('closed', 'Закрыта'), ('draft', 'Без тестирования')], default='published', max_length=127, verbose_name='Статус вакансии'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='unit',
            field=models.ForeignKey(blank=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='company.unit', verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='cities',
            field=models.ManyToManyField(related_name='vacancies', through='vacancies.VacancyToCity', to='company.City', verbose_name='Города'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='position',
            field=models.ForeignKey(blank=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='company.position', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='vacancytocity',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.city', verbose_name='Город'),
        ),
    ]
