# Generated by Django 3.2.15 on 2022-11-09 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0006_factoid'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('open', 'Открытый'), ('multi', 'Несколько ответов'), ('single', 'Один ответ')], default='single', max_length=64, verbose_name='Тип вопроса'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='poll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='vacancies.poll', verbose_name='Опросник'),
        ),
    ]
