# Generated by Django 3.2.15 on 2022-11-14 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancies', '0008_vacanciesinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='published_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='published_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_vacancies', to=settings.AUTH_USER_MODEL, verbose_name='Опубликовавший сотрудник'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='status',
            field=models.CharField(choices=[('published', 'Опубликована'), ('accepted', 'Принят'), ('closed', 'Закрыта'), ('draft', 'Без тестирования')], default='draft', max_length=127, verbose_name='Статус вакансии'),
        ),
    ]
