# Generated by Django 3.2.15 on 2022-11-16 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0009_auto_20221114_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='question',
            name='poll_template',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answer', to='vacancies.poll', verbose_name='Опросник'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poll',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='vacancies.vacancy', verbose_name='Вакансия'),
        ),
        migrations.CreateModel(
            name='QuestionToPollTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.polltemplate', verbose_name='Шаблон опросника')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.question', verbose_name='Вопрос')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionToPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.poll', verbose_name='Опросник')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.question', verbose_name='Вопрос')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='poll_templates',
            field=models.ManyToManyField(related_name='questions', through='vacancies.QuestionToPollTemplate', to='vacancies.PollTemplate', verbose_name='Шаблоны для опросника'),
        ),
        migrations.AddField(
            model_name='question',
            name='polls',
            field=models.ManyToManyField(related_name='questions', through='vacancies.QuestionToPoll', to='vacancies.Poll', verbose_name='Опросники'),
        ),
    ]
