# Generated by Django 3.2.15 on 2022-11-15 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0010_m2m_poll_poll_template_to_questions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VacanciesInfo',
        ),
    ]
