# Generated by Django 3.2.15 on 2023-04-04 07:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0011_delete_vacanciesinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyReserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='Название вакансии')),
                ('direction', models.CharField(max_length=255, verbose_name='Направление')),
                ('requirements', models.TextField(help_text='Стаж/оценка Top Performers/показатели', verbose_name='Требования')),
                ('priority', models.PositiveSmallIntegerField(default=1, help_text='Информация с наименьшим значением будет выдаваться первой.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Приоритет')),
            ],
            options={
                'verbose_name': 'Кадровый резерв',
                'verbose_name_plural': 'Кадровый резерв',
            },
        ),
    ]
