# Generated by Django 3.2.16 on 2023-05-11 11:59

import mdeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0012_vacancyreserve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancyreserve',
            name='requirements',
            field=mdeditor.fields.MDTextField(help_text='Стаж/оценка Top Performers/показатели', verbose_name='Требования'),
        ),
    ]
