# Generated by Django 3.2.16 on 2023-10-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vacancies', '0013_alter_vacancyreserve_requirements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True, verbose_name='Уровень вакансии')),
            ],
            options={
                'verbose_name': 'Уровень вакансии',
                'verbose_name_plural': 'Уровни вакансий',
            },

        ),

    ]
