# Generated by Django 3.2.16 on 2023-10-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vacancies', '0014_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240, verbose_name='Название причины статуса')),
                ('code', models.IntegerField(verbose_name='Код причины статуса')),
            ],
            options={
                'verbose_name': 'Причина открытия вакансии',
                'verbose_name_plural': 'Причины открытия вакансии',
            },
        ),
        migrations.CreateModel(
            name='VacancyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240, verbose_name='Название типа вакансии')),
                ('code', models.IntegerField(verbose_name='Код типа вакансии')),
            ],
            options={
                'verbose_name': 'Тип вакансии',
                'verbose_name_plural': 'Типы вакансий',
            },
        ),
        migrations.CreateModel(
            name='WorkContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240, verbose_name='Вид трудового договора')),
                ('code', models.IntegerField(verbose_name='Код трудового договора')),
            ],
            options={
                'verbose_name': 'Вид трудового договора',
                'verbose_name_plural': 'Виды трудового договора',
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240, verbose_name='Опыт работы')),
                ('code', models.IntegerField(verbose_name='Код опыта работы')),
            ],
            options={
                'verbose_name': 'Опыт работы',
                'verbose_name_plural': 'Опыт работы',
            },
        ),
        migrations.CreateModel(
            name='СontestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240, verbose_name='Название конкурса')),
                ('code', models.IntegerField(verbose_name='Код конкурса')),
            ],
            options={
                'verbose_name': 'Вид конкурса',
                'verbose_name_plural': 'Виды конкурсов',
            },
        ),
    ]
