# Generated by Django 3.2.16 on 2023-11-01 09:31

import django.db.models.deletion
from django.db import migrations, models


def change_rate_field(apps, schema_editor):
    Vacancy = apps.get_model('vacancies', 'Vacancy')
    Rate = apps.get_model('vacancies', 'Rate')
    for vacancy in Vacancy.objects.all():
        rate_obj, _ = Rate.objects.get_or_create(title=vacancy.rate_old)
        vacancy.rate = rate_obj
        vacancy.save()


class Migration(migrations.Migration):
    dependencies = [
        ('vacancies', '0015_reason_vacancytype_workcontract_workexperience_сontesttype'),
    ]

    operations = [
        migrations.RenameField(
            old_name='rate',
            new_name='rate_old',
            model_name='vacancy'
        ),
        migrations.AddField(
            model_name='vacancy',
            name='rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='vacancies.rate',
                                    verbose_name='Требуемый уровень'),
        ),
        migrations.RunPython(change_rate_field),
        migrations.RemoveField(
            model_name='vacancy',
            name='rate_old',
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.rate',
                                    verbose_name='Требуемый уровень'),
        ),

    ]
