# Generated by Django 3.2.16 on 2023-11-22 06:52

import datetime

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20231109_1356'),
        ('vacancies', '0016_alter_vacancy_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240, verbose_name='Название конкурса')),
                ('sap_id', models.CharField(blank=True, max_length=150, null=True, verbose_name='Id sap')),
            ],
            options={
                'verbose_name': 'Вид конкурса',
                'verbose_name_plural': 'Виды конкурса',
            },
        ),
        migrations.CreateModel(
            name='VacancyToOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.office', verbose_name='Адрес офиса')),
            ],
        ),
        migrations.RemoveField(
            model_name='vacancytocity',
            name='city',
        ),
        migrations.RemoveField(
            model_name='vacancytocity',
            name='vacancy',
        ),
        migrations.DeleteModel(
            name='СontestType',
        ),
        migrations.AlterModelOptions(
            name='vacancytype',
            options={'verbose_name': 'Тип вакансии', 'verbose_name_plural': 'Типы вакансий'},
        ),
        migrations.RemoveField(
            model_name='reason',
            name='code',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='vacancytype',
            name='code',
        ),
        migrations.RemoveField(
            model_name='workcontract',
            name='code',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='code',
        ),
        migrations.AddField(
            model_name='reason',
            name='sap_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Id sap'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='kpi',
            field=models.TextField(blank=True, null=True, verbose_name='Ключевые показатели'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies', to='vacancies.reason', verbose_name='Причина открытия вакансии'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='referral',
            field=models.BooleanField(default=False, verbose_name='Реферальная программа'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='release_date',
            field=models.DateField(default=datetime.date.today, validators=[django.core.validators.MinValueValidator(datetime.date(2023, 11, 22))], verbose_name='Дата освобождения ставки'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='vacancy_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_vacancies', to='vacancies.vacancytype', verbose_name='Тип вакансии'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='work_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies', to='vacancies.workcontract', verbose_name='Вид трудового договора'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='work_experience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experience_vacancies', to='vacancies.workexperience', verbose_name='Опыт работы'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='workplace_number',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Номер рабочего места'),
        ),
        migrations.AddField(
            model_name='vacancytype',
            name='sap_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Id sap'),
        ),
        migrations.AddField(
            model_name='workcontract',
            name='sap_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Id sap'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='sap_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Id sap'),
        ),
        migrations.AlterField(
            model_name='reason',
            name='title',
            field=models.CharField(max_length=240, verbose_name='Причина открытия вакансии'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='vacancies.rate', verbose_name='Требуемый уровень'),
        ),
        migrations.AlterField(
            model_name='vacancytype',
            name='title',
            field=models.CharField(max_length=240, verbose_name='Тип вакансии'),
        ),
        migrations.DeleteModel(
            name='VacancyToCity',
        ),
        migrations.AddField(
            model_name='vacancytooffice',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.vacancy', verbose_name='Вакансия'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='offices',
            field=models.ManyToManyField(related_name='vacancies', through='vacancies.VacancyToOffice', to='company.Office', verbose_name='Адреса офисов'),
        ),
    ]
