# Generated by Django 3.2.16 on 2023-11-30 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancies', '0018_auto_20231125_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='purpose',
            field=models.TextField(blank=True, verbose_name='Цель должности'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='benefits',
            field=models.TextField(help_text='Предлагаемые плюшки (печеньки/кофе/дружный коллектив)', null=True, verbose_name='Мы предлагаем'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='duties',
            field=models.TextField(help_text='Задачи/должностные обязанности', null=True, verbose_name='Задачи'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='reason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies', to='vacancies.reason', verbose_name='Причина открытия вакансии'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='selection_type',
            field=models.CharField(choices=[('mass', 'Массовый'), ('professional', 'Профессиональный')], default='professional', max_length=217, verbose_name='Тип подбора'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='skills',
            field=models.TextField(help_text='Умения/навыки/опыт', null=True, verbose_name='Ожидания'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='work_contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies', to='vacancies.workcontract', verbose_name='Вид трудового договора'),
        ),
        migrations.AlterField(
            model_name='vacancytooffice',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Является ли офис главным'),
        ),
    ]
