# Generated by Django 3.2.16 on 2023-11-28 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancies', '0019_auto_20231129_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='recruiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruiter_vacancies', to=settings.AUTH_USER_MODEL, verbose_name='Рекрутер'),
        ),
    ]
