# Generated by Django 3.2.16 on 2023-12-05 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancies', '0021_auto_20231204_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='sap_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Id sap'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_vacancies', to=settings.AUTH_USER_MODEL, verbose_name='Опубликовавший сотрудник'),
        ),
    ]
