# Generated by Django 3.2.16 on 2023-12-06 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancies', '0023_auto_20231205_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='selection_type',
            field=models.CharField(choices=[('mass', 'Массовый'), ('professional', 'Профессиональный')], default='professional', max_length=217, verbose_name='Тип подбора'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='published_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_vacancies', to=settings.AUTH_USER_MODEL, verbose_name='Опубликовавший сотрудник'),
        ),
    ]
