# Generated by Django 3.2.15 on 2022-10-13 08:54

from django.db import migrations, models

import core.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.file_path, verbose_name='Изображение'),
        ),
    ]
