# Generated by Django 3.2.15 on 2022-10-28 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_company_app_models_instead_users'),
        ('users', '0005_auto_20221024_1207'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
        migrations.RemoveField(
            model_name='companyunit',
            name='parent',
        ),
        migrations.DeleteModel(
            name='InfoFile',
        ),
        migrations.RemoveField(
            model_name='position',
            name='company_units',
        ),
        migrations.RemoveField(
            model_name='position',
            name='targets',
        ),
        migrations.RemoveField(
            model_name='positiontocompanyunit',
            name='company_unit',
        ),
        migrations.RemoveField(
            model_name='positiontocompanyunit',
            name='position',
        ),
        migrations.RemoveField(
            model_name='positiontotargetposition',
            name='position',
        ),
        migrations.RemoveField(
            model_name='positiontotargetposition',
            name='target',
        ),
        migrations.DeleteModel(
            name='CompanyUnit',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.DeleteModel(
            name='PositionToCompanyUnit',
        ),
        migrations.DeleteModel(
            name='PositionToTargetPosition',
        ),
    ]
