# Generated by Django 3.2.16 on 2023-05-12 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20230417_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='reserved_until',
        ),
    ]
