# Generated by Django 3.2.16 on 2023-12-01 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_user_reserved_until'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('is_manager', 'This user is manager'), ('is_hr', 'This user is HR'), ('is_head_hr', 'This user is head of HR')), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
