# Generated by Django 3.2.16 on 2023-12-12 09:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20231212_0935'),
        ('users', '0010_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='company.city', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='user',
            name='fired_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата увольнения'),
        ),
        migrations.AddField(
            model_name='user',
            name='hired_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата устройства'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_decret',
            field=models.BooleanField(default=False, verbose_name='Декрет'),
        ),
        migrations.AddField(
            model_name='user',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subordinates', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель'),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='company.position', verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='user',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='company.unit', verbose_name='Подразделение'),
        ),
    ]
