# Generated by Django 3.2.16 on 2023-12-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20231212_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_image_url',
            field=models.URLField(blank=True, help_text='Кастомное фото для сервиса. Если проставлено - будет использоваться внутри сервиса.', verbose_name='Ссылка на фото внутри сервиса'),
        ),
    ]
