# Generated by Django 3.2.16 on 2023-11-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saprequest',
            name='endpoint',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
