# Generated by Django 3.2.16 on 2023-12-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0002_saprequest_endpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='saprequest',
            name='task',
            field=models.CharField(blank=True, help_text='Название celery task, которым был текущий sap request создан', max_length=240, null=True),
        ),
    ]
