# Generated by Django 3.2.15 on 2022-10-24 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerType',
            fields=[
                ('slug', models.SlugField(choices=[('expert', 'Экспертная'), ('manager', 'Управленческая'), ('project', 'Проектная')], primary_key=True, serialize=False, verbose_name='Тип карьеры')),
                ('color', models.CharField(choices=[('primary', 'Зеленый'), ('primaryLight', 'Светло-зеленый'), ('secondary', 'Фиолетовый'), ('secondaryLight', 'Светло-фиолетовый'), ('orangeLight', 'Светло-оранжевый'), ('gray', 'Серый'), ('blue', 'Голубой')], max_length=50, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Тип карьеры',
                'verbose_name_plural': 'Типы карьеры',
            },
        ),
    ]
