# Generated by Django 3.2.15 on 2022-11-16 09:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial_core_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('priority', models.PositiveSmallIntegerField(default=10, help_text='Информация с наименьшим значением будет выдаваться первой. Диапазон значений: [1;10]', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Приоритет')),
            ],
            options={
                'verbose_name': 'Частый вопрос',
                'verbose_name_plural': 'Частые вопросы',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('slug', models.SlugField(choices=[('expert_vacancies_list', 'Экспертный тип карьеры. Список вакансий'), ('manager_vacancies_list', 'Управленческий тип карьеры. Список вакансий'), ('vacancy_description', 'Описание вакансии'), ('submitted_requests', 'Отправленные заявки'), ('incoming_requests', 'Входящие заявки'), ('my_vacancies_boss', 'Руководитель. Мои вакансии'), ('vacancies_hr', 'HR. Вакансии'), ('head_hr_vacancies_list', 'Head HR. Список вакансий')], max_length=70, primary_key=True, serialize=False, verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
            },
        ),
        migrations.CreateModel(
            name='InfoToSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.info', verbose_name='Частый вопрос')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.section', verbose_name='Раздел')),
            ],
        ),
        migrations.AddField(
            model_name='info',
            name='sections',
            field=models.ManyToManyField(related_name='info', through='core.InfoToSection', to='core.Section', verbose_name='Разделы'),
        ),
    ]
