# Generated by Django 3.2.15 on 2023-05-10 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20221115_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careertype',
            name='color',
        ),
    ]
