# Generated by Django 3.2.16 on 2023-12-14 07:36

from django.db import migrations, models

import core.utils


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_careertype_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=core.utils.file_path, verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
    ]
